# Logrotate
- name: 'Deploy logrotate.conf'
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0640

- name: 'Deploy logrotate.d'
  copy:
    src: "{{ item }}"
    dest: /etc/logrotate.d
    owner: root
    group: root
    mode: 0640
  with_fileglob:
    - logrotate.d/*

